# Generated by Django 3.2 on 2023-07-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_AlterField'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personfilmwork',
            name='role',
            field=models.CharField(blank=True, choices=[('actor', 'Actor'), ('writer', 'Writer'), ('director', 'Director')], max_length=15, verbose_name='Role'),
        ),
    ]
